### PR TITLE
binja: use colors for diff info in trace panel

### PR DESCRIPTION
**Pull request by thebendavis**
This is an initial version prototype of using colors to provide diff info in trace view, which we used to support the hackathon event. Going forward, current considerations include: 1) improving the diff algorithm to reason about sequences (rather than just membership/uniqueness), as well as 2) a broader consideration of the use of color vs. binary ninja themes. E.g. the colors here work well when running Binary Ninja in the Classic (light) theme, but make the traces harder to read when running Binary Ninja in a dark theme.

### CODE REVIEW

**Comment by thebendavis** [comment]
Here's an example of a colorized diff in the trace view:

Screenshot 2024-03-07 at 1 20 18 PM

**Comment by jim-carciofini** [comment]
That is nice!  I found a diff lib that I should be can use to make this even better (your issue (1)). Do you want me to do it on this branch, or wait four your merge to master?

**Comment by thebendavis** [comment]
> That is nice! I found a diff lib that I can use to make this even better (your issue (1)). Do you want me to do it on this branch, or wait for your merge to master?

@jim-carciofini great! I opened this PR to capture what I used at the event, but at this point if you'd like to take over to complete and merge this feature then that'd be wonderful - thanks! Feel free to update this branch however you see fit.

The question about supporting multiple themes etc. is a broader topic that doesn't need to be resolved in this MR IMO.

**Comment by jim-carciofini** [comment]
@danmatichuk what the status of the dm/hackathon-mar-2024 branch? Is it stable? I just realized this PR is branched off that and not master.

**Comment by jim-carciofini** [comment]
After thinking about it a bit more, I am inclined to cherry pick the commits related to the GUI in a new branch, merge it to master and abandon this PR.

**Comment by jim-carciofini** [comment]
Abandoning this PR. The GUI changes were cherry picked into PR #376 and merged to master.

**Pull request closed without merging**
