### PR TITLE
Update to the latest crucible/what4

### PR DESCRIPTION
**Pull request by travitch**
This deals with the demotion of Nat from a base type and includes corresponding
updates to semmc/asl-translator/macaw and others.

### CODE REVIEW

**Comment by travitch** [comment]
@danmatichuk This could probably use another pair of eyes. The tests pass, but I'm a bit nervous about the nat->int and int->nat conversions. I think it should always be fine, except possibly for models coming back from the solver. I just map any negative values to the positive range, but perhaps that could generate a false conflict? We could potentially assert some side conditions when asking for models.

**Comment by travitch** [comment]
Actually, I think we are getting a safe bound - I'm allocating our symbolic block IDs using `freshNat`, which properly constrains the underlying symbolic integer.

**Comment by travitch** [comment]
Ah okay, here is a question for @danmatichuk - do we ever make a fresh LLVMPointer struct (in the what4 base types struct sense)? Or do we ever have an uninterpreted function that magically introduces one? If so, we would probably need to project out the (now Integer) block ID field and constrain it

**Comment by danmatichuk** [comment]
The only place I can think of is the result of pointer operations, when undefined, is the result of an uninterpreted function which yields an LLVPointer struct.

https://github.com/GaloisInc/pate/blob/825893b5c3e87d7da8663b4c95d95e038cb11702/src/Pate/Memory/MemTrace.hs#L212

**Pull request merged**
